### ISSUE TITLE
local YAMLException: duplicated mapping key at line 25, column -607

### ISSUE THREAD

**Issue by gHashTag** [graphcool-examples/react-graphql#57]
I decided to rebuild the project and got this error. How to fix?

```sh
 ~/authentication-with-facebook-and-apollo/server  graphcool deploy export DEBUG="*"                                                                          ✔  4539  20:26:55
  config CWD /Users/xyz/authentication-with-facebook-and-apollo/server +0ms
  config HOME /Users/xyz +3ms
  config definitionDir /Users/xyz/authentication-with-facebook-and-apollo/server +0ms
  config definitionPath /Users/xyz/authentication-with-facebook-and-apollo/server/graphcool.yml +0ms
  config homepath /Users/xyz/.graphcoolrc +0ms
  config localRCPath /Users/xyz/authentication-with-facebook-and-apollo/server/.graphcoolrc +0ms
  config globalRCPath /Users/xyz/.graphcoolrc +0ms
  cli command id deploy:export +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/xyz/Library/Caches/graphcool/plugins.json +0ms
  cli:plugincache Got plugin from cache +2ms
  cli:plugincache /Users/xyz/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  cli:plugincache Got plugin from cache +4ms
  cli:plugincache /Users/xyz/Library/Caches/graphcool/plugins.json +10ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/xyz/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +14ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +631ms
  plugin required command +635ms
  deploy run +0ms
? Please choose the cluster you want to deploy to (Use arrow keys)

  Shared Clusters:
❯ shared-eu-west-1
  shared-ap-northeast-1
  shared-us-west-2

  Local (docker):
  local YAMLException: duplicated mapping key at line 25, column -607:
    functions:
    ^
    at generateError (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at storeMappingPair (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:308:7)
    at readBlockMapping (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:1071:9)
    at composeNode (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/usr/local/lib/node_modules/graphcool/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at ProjectDefinitionClass.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/ProjectDefinition/ProjectDefinition.ts:166:23)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/ProjectDefinition.js:32:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/ProjectDefinition.js:13:53)
    at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/ProjectDefinition.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/ProjectDefinition.js:3:12)
    at ProjectDefinitionClass.checkNodeModules (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/ProjectDefinition.js:177:16)
Exiting with code: 1
```

**Comment by marktani** [comment]
Looks like you have the `functions` key mentioned twice in your `graphcool.yml` file. Please remove one of them.

If the issue persists, please share your `graphcool.yml` file.

**Comment by gHashTag** [comment]
types: ./types.graphql



```yaml
functions:
  facebookAuthentication:
    handler:
      code:
        src: ./src/facebookAuthentication.ts
    type: resolver
    schema: ./src/facebookAuthentication.graphql
  loggedInUser:
    handler:
      code:
        src: ./src/loggedInUser.ts
    type: resolver
    schema: ./src/loggedInUser.graphql

permissions:
- operation: "*"
```

**Comment by gHashTag** [comment]
again rebuild project and fixed this issue
